# Generated by Django 2.2b1 on 2019-03-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.PositiveIntegerField(default=22222222),
            preserve_default=False,
        ),
    ]
