# Generated by Django 2.2b1 on 2019-03-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
    ]
