# Generated by Django 2.2b1 on 2019-03-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190331_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default='testtest', max_length=255),
            preserve_default=False,
        ),
    ]
