# Generated by Django 2.0.13 on 2019-05-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_myuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.CharField(default='kelibia', max_length=255),
            preserve_default=False,
        ),
    ]
