# Generated by Django 2.0.13 on 2019-05-04 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190504_2356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleSummary',
        ),
    ]
